#page title
page_title                                : Sage Vote           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6744004947          # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ca                  # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                     # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                     # Enter Google Play Store URL.
presskit_download_link                    :                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sage Vote                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An educational board game that teaches Canadian politics through an interactive journey to the polling station. Roll dice, navigate paths, and learn about democracy along the way.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Carolyn Moen, Nikki Hearns & Hannah Downes                                
your_link                                 :                      
your_city                                 : Nanaimo                                
email_address                             : cmcaughren@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Learning Through Play
    description                           : Discover the Canadian political landscape in an engaging, interactive board-game format that makes learning about democracy fun and accessible for everyone. 
    fontawesome_icon_name                 : dice
    
  - title                                 : Canadian Political Education
    description                           : Access curated resources about Canada's electoral system, political processes, and civic responsibilities.
    fontawesome_icon_name                 : flag
    
  - title                                 : Digital Board Game
    description                           : Roll the dice, draw cards, and navigate your way across the board on your journey to cast your ballot in the Canadian election.
    fontawesome_icon_name                 : route

  - title                                 : Voter Registration
    description                           : Begin your journey by learning about Canadian voter registration and the ID requirements of the Canadian Federal Election.
    fontawesome_icon_name                 : id-card

  - title                                 : Knowledge Notebook
    description                           : Collect educational resources in your digital notebook as you play, building your personal reference guide to Canadian politics.
    fontawesome_icon_name                 : book-open

  - title                                 : Political Scenario Cards
    description                           : Draw cards featuring fun political scenarios with outcomes determined by dice rolls, creating a different gameplay experience each time you play. 
    fontawesome_icon_name                 : vote-yea



# Theme Settings
topbar_color                              : "#ABC19B"           # Sage green primary color
topbar_transparency                       : 0.9
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ABC19B"           # Sage green overlay
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#F5F9F2"           # Light sage background

link_color                                : "#8B88F8"           # Periwinkle for links

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#87A771"           # Sage green for feature titles
feature_text_color                        : "#333333"           # Darker text for better readability

feature_icons_foreground_color            : "#8B88F8"           # Periwinkle for icon foreground
feature_icons_background_color            : "#B6B4FB"           # Light periwinkle background

social_icons_foreground_color             : "#87A771"           # Sage green for social icons
social_icons_background_color             : "#ABC19B"           # Light sage background

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
